name: keras
channels:
- conda-forge
- defaults
dependencies:
- graphviz
- ipython
- matplotlib
- notebook
- numpy
- pillow
- pip
- scikit-learn
- tensorflow
- theano
- keras
- pip:
  - pydot-ng
  - graphviz  
